Partie 1 : Listes Python vs tableaux NumPy
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8
1) Créer une liste Python stockant ces températures;

In [1]:
liste = [24.5, 25.1, 26.3, 27.0, 25.8]
liste

[24.5, 25.1, 26.3, 27.0, 25.8]

2) Créer un tableau NumPy équivalent stockant ces températures ;

In [3]:
import numpy as np

tab = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
tab

array([24.5, 25.1, 26.3, 27. , 25.8])

3) Effectuer une multiplication par 2 sur ces deux collections;

In [4]:
mult_liste = liste * 2
mult_liste

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]

In [6]:
mult_tab = tab * 2
mult_tab

array([49. , 50.2, 52.6, 54. , 51.6])

Quelle différence observe-t-on ? 

on constate que avec les liste ca a dipluquer la liste alors que avec le tableau ca a appliquer la multiplication 

Partie 2 – Création des données
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [8]:
tab = np.zeros(10)
tab

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2) Créer un tableau contenant 10 valeurs égales à 1.

In [9]:
tab = np.ones(10)
tab

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3) Créer un tableau de 10 valeurs initialisées à 25.

In [10]:
tab = np.full(10,25)
tab

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

4) Créer une matrice identité de taille 5 × 5.

In [22]:
tab = np.eye(5,5)
tab

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

5) Créer les 24 heures (de 0 à 23) de mesure d’une journée

In [27]:
tab = np.arange(24)
tab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [28]:
tab = np.linspace(20, 30, 10)
tab

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [38]:
np.random.seed(42)
tab = np.random.rand(100)
tab

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
       0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
       0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041,
       0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
       0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249,
       0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
       0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446,
       0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998,
       0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033,
       0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
       0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694,
       0.77224477, 0.19871568, 0.00552212, 0.81546143, 0.70685

Partie 3 – Exploration des tableaux
1) Créer aléatoirement un tableau représentant les 24 températures d'une journée :

In [55]:
temperature = np.random.uniform(24,35,24)
temperature

array([31.98551247, 33.86821286, 33.75795067, 32.578631  , 31.06234811,
       24.92553961, 25.77791586, 33.88409607, 30.67071966, 24.10116757,
       25.11618697, 31.29851946, 24.05567742, 25.76888857, 30.03607168,
       31.61084717, 31.17157385, 26.4669624 , 31.83397143, 26.60973996,
       27.57939668, 32.21140546, 31.14596189, 33.34145752])

2) Déterminer les propriétés suivantes du tableau
a) nombre de dimensions 

In [49]:
np.ndim(temperature)

1

b) nombre de valeurs ;

In [44]:
np.size(temperature)

24

c) type des données ;

In [47]:
temperature.dtype

dtype('float64')

d) forme du tableau.

In [48]:
temperature.shape

(24,)

Partie 4 – Indexation et slicing
Considérant le tableau représentant les 24 températures d'une journée, afficher :

1) la première mesure ;

In [57]:
print(temperature[0])

31.985512467572633


In [ ]:
2) la dernière mesure 

In [59]:
print(temperature[23])

33.341457515435955


3) la température de 8h ;

In [60]:
print(temperature[8])

30.67071965625549


4) les températures de 8h à 12h ;

In [61]:
print(temperature[8:12])

[30.67071966 24.10116757 25.11618697 31.29851946]


5) les températures des 6 premières heures ;

In [62]:
print(temperature[0:6])

[31.98551247 33.86821286 33.75795067 32.578631   31.06234811 24.92553961]


6) les températures des heures paires.

In [63]:
print(temperature)

[31.98551247 33.86821286 33.75795067 32.578631   31.06234811 24.92553961
 25.77791586 33.88409607 30.67071966 24.10116757 25.11618697 31.29851946
 24.05567742 25.76888857 30.03607168 31.61084717 31.17157385 26.4669624
 31.83397143 26.60973996 27.57939668 32.21140546 31.14596189 33.34145752]


In [65]:
print(temperature[::2])

[31.98551247 33.75795067 31.06234811 25.77791586 30.67071966 25.11618697
 24.05567742 30.03607168 31.17157385 31.83397143 27.57939668 31.14596189]
