Partie 1 : Listes Python vs tableaux NumPy
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8
1) Créer une liste Python stockant ces températures;

In [1]:
liste = [24.5, 25.1, 26.3, 27.0, 25.8]
liste

[24.5, 25.1, 26.3, 27.0, 25.8]

2) Créer un tableau NumPy équivalent stockant ces températures ;

In [3]:
import numpy as np

tab = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
tab

array([24.5, 25.1, 26.3, 27. , 25.8])

3) Effectuer une multiplication par 2 sur ces deux collections;

In [4]:
mult_liste = liste * 2
mult_liste

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]

In [6]:
mult_tab = tab * 2
mult_tab

array([49. , 50.2, 52.6, 54. , 51.6])

Quelle différence observe-t-on ? 

on constate que avec les liste ca a dipluquer la liste alors que avec le tableau ca a appliquer la multiplication 

Partie 2 – Création des données
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [8]:
tab = np.zeros(10)
tab

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2) Créer un tableau contenant 10 valeurs égales à 1.

In [9]:
tab = np.ones(10)
tab

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3) Créer un tableau de 10 valeurs initialisées à 25.

In [10]:
tab = np.full(10,25)
tab

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

4) Créer une matrice identité de taille 5 × 5.

In [22]:
tab = np.eye(5,5)
tab

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

5) Créer les 24 heures (de 0 à 23) de mesure d’une journée

In [27]:
tab = np.arange(24)
tab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

6) Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C

In [28]:
tab = np.linspace(20, 30, 10)
tab

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

7) Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles

In [38]:
np.random.seed(42)
tab = np.random.rand(100)
tab

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258,
       0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
       0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914,
       0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
       0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041,
       0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
       0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249,
       0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
       0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446,
       0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998,
       0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033,
       0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
       0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694,
       0.77224477, 0.19871568, 0.00552212, 0.81546143, 0.70685

Partie 3 – Exploration des tableaux
1) Créer aléatoirement un tableau représentant les 24 températures d'une journée :

In [95]:
temperature = np.random.uniform(24,45,24)
temperature

array([38.4982914 , 24.82555494, 40.78761838, 37.18590818, 25.71693967,
       42.34515111, 43.33832041, 25.28263716, 29.81443061, 40.93022688,
       39.7134535 , 27.87494141, 28.39633579, 31.77991416, 34.17498269,
       36.9833502 , 31.74718643, 33.71322904, 39.6968897 , 24.77034726,
       29.30117583, 38.9803413 , 42.79934359, 34.74522628])

2) Déterminer les propriétés suivantes du tableau
a) nombre de dimensions 

In [49]:
np.ndim(temperature)

1

b) nombre de valeurs ;

In [44]:
np.size(temperature)

24

c) type des données ;

In [47]:
temperature.dtype

dtype('float64')

d) forme du tableau.

In [48]:
temperature.shape

(24,)

Partie 4 – Indexation et slicing
Considérant le tableau représentant les 24 températures d'une journée, afficher :

1) la première mesure ;

In [57]:
print(temperature[0])

31.985512467572633


In [ ]:
2) la dernière mesure 

In [59]:
print(temperature[23])

33.341457515435955


3) la température de 8h ;

In [60]:
print(temperature[8])

30.67071965625549


4) les températures de 8h à 12h ;

In [61]:
print(temperature[8:12])

[30.67071966 24.10116757 25.11618697 31.29851946]


5) les températures des 6 premières heures ;

In [62]:
print(temperature[0:6])

[31.98551247 33.86821286 33.75795067 32.578631   31.06234811 24.92553961]


6) les températures des heures paires.

In [72]:
print(temperature)

[34.52180628 33.09293765 25.49879629 29.88345285 28.24323788 27.90383429
 39.56816888 30.28956359 38.27274488 34.09821802 36.71698086 32.04219349
 33.23046215 31.8802831  27.1238878  35.55923384 28.4923578  24.38905546
 34.32755673 26.83377087 39.04733735 39.26285723 38.63783024 29.9225392 ]


In [65]:
print(temperature[::2])

[31.98551247 33.75795067 31.06234811 25.77791586 30.67071966 25.11618697
 24.05567742 30.03607168 31.17157385 31.83397143 27.57939668 31.14596189]


Partie 5 – Filtrage booléen
Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les
situations inhabituelles.

1) Afficher les températures supérieures à 30 °C

In [73]:
print(temperature[temperature > 30])

[34.52180628 33.09293765 39.56816888 30.28956359 38.27274488 34.09821802
 36.71698086 32.04219349 33.23046215 31.8802831  35.55923384 34.32755673
 39.04733735 39.26285723 38.63783024]


2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C

In [80]:
temperature[(temperature >= 20) & (temperature <= 30)]

array([25.49879629, 29.88345285, 28.24323788, 27.90383429, 27.1238878 ,
       28.4923578 , 24.38905546, 26.83377087, 29.9225392 ])

3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale.
Déterminer anomalies, un tableau de booléen précisant les anomalies

In [84]:
anomalies = temperature > 35
anomalies

array([False, False, False, False, False, False,  True, False,  True,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True,  True,  True, False])

4) Déterminer le nombre de températures anormales à l’aide de la variable anomalies

In [90]:
np.sum(anomalies)

np.int64(7)

Partie 6 – Manipulation des dimensions
On suppose qu’on a 5 capteurs.
1) Créer aléatoirement la matrice représentant les températures mesurées par ces capteurs durant une journée

In [109]:
temperature = np.random.uniform(24, 45, (5, 24))
temperature

array([[35.17438319, 26.25061224, 33.3956597 , 35.1849626 , 29.09188058,
        29.65410785, 31.92296743, 24.42149515, 30.76366248, 28.44040815,
        30.8774444 , 26.51500477, 42.7010729 , 36.46544152, 38.2611487 ,
        40.57259601, 34.46728618, 25.82532605, 35.27923738, 36.32366348,
        39.65422896, 33.06485047, 26.67918636, 29.95929402],
       [31.62472822, 37.56426207, 35.9863444 , 31.47803124, 44.71682022,
        36.72127121, 28.98176263, 26.13743193, 27.21004192, 29.1651123 ,
        27.37430884, 27.91790751, 29.98699854, 27.6408455 , 42.83207392,
        25.68490866, 35.01473918, 32.61833337, 44.62995096, 26.35281695,
        32.35496758, 44.3588791 , 42.17564964, 41.15851349],
       [29.41595937, 27.58863934, 38.04150762, 43.51689577, 35.69202075,
        36.00386648, 29.87956097, 40.1593516 , 27.92791872, 30.79726396,
        32.93416521, 34.65981795, 29.09060438, 26.41157332, 36.82302089,
        30.06124162, 36.20600265, 27.24161702, 34.10394214, 35.18437808,
  

2) Transformer la matrice en un tableau unidimensionnel

In [111]:
tableau_id = temperature.flatten()
tableau_id

array([35.17438319, 26.25061224, 33.3956597 , 35.1849626 , 29.09188058,
       29.65410785, 31.92296743, 24.42149515, 30.76366248, 28.44040815,
       30.8774444 , 26.51500477, 42.7010729 , 36.46544152, 38.2611487 ,
       40.57259601, 34.46728618, 25.82532605, 35.27923738, 36.32366348,
       39.65422896, 33.06485047, 26.67918636, 29.95929402, 31.62472822,
       37.56426207, 35.9863444 , 31.47803124, 44.71682022, 36.72127121,
       28.98176263, 26.13743193, 27.21004192, 29.1651123 , 27.37430884,
       27.91790751, 29.98699854, 27.6408455 , 42.83207392, 25.68490866,
       35.01473918, 32.61833337, 44.62995096, 26.35281695, 32.35496758,
       44.3588791 , 42.17564964, 41.15851349, 29.41595937, 27.58863934,
       38.04150762, 43.51689577, 35.69202075, 36.00386648, 29.87956097,
       40.1593516 , 27.92791872, 30.79726396, 32.93416521, 34.65981795,
       29.09060438, 26.41157332, 36.82302089, 30.06124162, 36.20600265,
       27.24161702, 34.10394214, 35.18437808, 25.08829427, 31.06

In [116]:
np.ndim(tableau_id)

1

3) Déterminer la transposée de la matrice

In [113]:
temperature.transpose()

array([[35.17438319, 31.62472822, 29.41595937, 44.78916488, 27.4367748 ],
       [26.25061224, 37.56426207, 27.58863934, 30.76943074, 27.44958176],
       [33.3956597 , 35.9863444 , 38.04150762, 41.00736336, 41.10606912],
       [35.1849626 , 31.47803124, 43.51689577, 29.34745375, 37.96914163],
       [29.09188058, 44.71682022, 35.69202075, 38.31155717, 34.98437392],
       [29.65410785, 36.72127121, 36.00386648, 39.96478506, 31.53544017],
       [31.92296743, 28.98176263, 29.87956097, 36.50841355, 42.42121136],
       [24.42149515, 26.13743193, 40.1593516 , 33.90309996, 32.24134726],
       [30.76366248, 27.21004192, 27.92791872, 32.6486592 , 41.14858823],
       [28.44040815, 29.1651123 , 30.79726396, 31.3262336 , 33.22183308],
       [30.8774444 , 27.37430884, 32.93416521, 43.52011203, 31.91583302],
       [26.51500477, 27.91790751, 34.65981795, 41.44300756, 33.7162755 ],
       [42.7010729 , 29.98699854, 29.09060438, 44.26556512, 30.32893536],
       [36.46544152, 27.6408455 , 26.4

In [115]:
temperature.ndim

2

4) Extraire toutes les mesures du capteur 1 ;

In [119]:
temperature[0,:]

array([35.17438319, 26.25061224, 33.3956597 , 35.1849626 , 29.09188058,
       29.65410785, 31.92296743, 24.42149515, 30.76366248, 28.44040815,
       30.8774444 , 26.51500477, 42.7010729 , 36.46544152, 38.2611487 ,
       40.57259601, 34.46728618, 25.82532605, 35.27923738, 36.32366348,
       39.65422896, 33.06485047, 26.67918636, 29.95929402])

5) Extraire toutes les mesures du capteur 5 

In [120]:
temperature[4,:]

array([27.4367748 , 27.44958176, 41.10606912, 37.96914163, 34.98437392,
       31.53544017, 42.42121136, 32.24134726, 41.14858823, 33.22183308,
       31.91583302, 33.7162755 , 30.32893536, 39.69979698, 34.55712819,
       28.8764666 , 42.89106604, 32.06171565, 35.41461008, 43.03591433,
       37.10899791, 26.45485885, 43.7364746 , 37.18186911])