Partie 1 : Listes Python vs tableaux NumPy
On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8
1) Créer une liste Python stockant ces températures;

In [1]:
liste = [24.5, 25.1, 26.3, 27.0, 25.8]
liste

[24.5, 25.1, 26.3, 27.0, 25.8]

2) Créer un tableau NumPy équivalent stockant ces températures ;

In [3]:
import numpy as np

tab = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
tab

array([24.5, 25.1, 26.3, 27. , 25.8])

3) Effectuer une multiplication par 2 sur ces deux collections;

In [4]:
mult_liste = liste * 2
mult_liste

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]

In [6]:
mult_tab = tab * 2
mult_tab

array([49. , 50.2, 52.6, 54. , 51.6])

Quelle différence observe-t-on ? 

on constate que avec les liste ca a dipluquer la liste alors que avec le tableau ca a appliquer la multiplication 

Partie 2 – Création des données
1) Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [8]:
tab = np.zeros(10)
tab

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2) Créer un tableau contenant 10 valeurs égales à 1.

In [9]:
tab = np.ones(10)
tab

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

3) Créer un tableau de 10 valeurs initialisées à 25.

In [10]:
tab = np.full(10,25)
tab

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])